// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	TokenHash []byte
	UserID    int32
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Recommend struct {
	UserID   int32
	TagID    int32
	MatchInt int32
}

type Tag struct {
	TagID   int32
	TagName string
}

type User struct {
	UserID   int32
	UserName string
	Password string
	Role     string
}
