// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	TokenHash []byte
	UserID    int32
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type FeedbackAnswer struct {
	SubmissionID pgtype.UUID
	FormID       int64
	QuestionID   int64
	Score        int32
}

type FeedbackForm struct {
	ID           int64
	FormKey      string
	Version      int32
	Title        string
	Status       string
	CooldownDays int32
	CreatedAt    pgtype.Timestamptz
}

type FeedbackInterestSnapshot struct {
	SubmissionID pgtype.UUID
	Rank         int32
	TagID        pgtype.Int4
	TagName      string
	MatchInt     int32
}

type FeedbackPrompt struct {
	ID         pgtype.UUID
	FormID     int64
	UserID     int32
	Status     string
	Stage      string
	ShownAt    pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

type FeedbackQuestion struct {
	ID                  int64
	FormID              int64
	QuestionKey         string
	QuestionText        string
	SortOrder           int32
	IsRequired          bool
	DisplayIfQuestionID pgtype.Int8
	DisplayIfScoreMax   pgtype.Int4
}

type FeedbackSubmission struct {
	ID          pgtype.UUID
	FormID      int64
	UserID      int32
	PromptID    pgtype.UUID
	Status      string
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

type Recommend struct {
	UserID   int32
	TagID    int32
	MatchInt int32
}

type Tag struct {
	TagID   int32
	TagName string
}

type User struct {
	UserID   int32
	UserName string
	Password string
	Role     string
}
