// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recommendations.sql

package dbgen

import (
	"context"
)

const listRecommendations = `-- name: ListRecommendations :many
SELECT r."tag_ID", t.tag_name, r.match_int
FROM recommend r JOIN tag t ON t."tag_ID" = r."tag_ID"
WHERE r."user_ID" = $1 ORDER BY r."tag_ID"
`

type ListRecommendationsRow struct {
	TagID    int32
	TagName  string
	MatchInt int32
}

func (q *Queries) ListRecommendations(ctx context.Context, userID int32) ([]ListRecommendationsRow, error) {
	rows, err := q.db.Query(ctx, listRecommendations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecommendationsRow{}
	for rows.Next() {
		var i ListRecommendationsRow
		if err := rows.Scan(&i.TagID, &i.TagName, &i.MatchInt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserForRecommendation = `-- name: LockUserForRecommendation :one
SELECT "user_ID" FROM "user" WHERE "user_ID" = $1 FOR UPDATE
`

func (q *Queries) LockUserForRecommendation(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, lockUserForRecommendation, userID)
	var user_ID int32
	err := row.Scan(&user_ID)
	return user_ID, err
}

const upsertRecommendation = `-- name: UpsertRecommendation :exec
INSERT INTO recommend ("user_ID", "tag_ID", match_int) VALUES ($1, $2, $3)
ON CONFLICT ("user_ID", "tag_ID") DO UPDATE SET match_int = EXCLUDED.match_int
`

type UpsertRecommendationParams struct {
	UserID   int32
	TagID    int32
	MatchInt int32
}

func (q *Queries) UpsertRecommendation(ctx context.Context, arg UpsertRecommendationParams) error {
	_, err := q.db.Exec(ctx, upsertRecommendation, arg.UserID, arg.TagID, arg.MatchInt)
	return err
}
