// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO auth_session (token_hash, "user_ID", expires_at) VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    int32
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM auth_session WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM auth_session WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const findSessionUser = `-- name: FindSessionUser :one
SELECT u."user_ID", u.user_name, u.role, s.expires_at
FROM auth_session s JOIN "user" u ON u."user_ID" = s."user_ID"
WHERE s.token_hash = $1 AND s.expires_at > $2
`

type FindSessionUserParams struct {
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

type FindSessionUserRow struct {
	UserID    int32
	UserName  string
	Role      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) FindSessionUser(ctx context.Context, arg FindSessionUserParams) (FindSessionUserRow, error) {
	row := q.db.QueryRow(ctx, findSessionUser, arg.TokenHash, arg.ExpiresAt)
	var i FindSessionUserRow
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Role,
		&i.ExpiresAt,
	)
	return i, err
}
