// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signup.sql

package dbgen

import (
	"context"
)

const createInitialRecommendation = `-- name: CreateInitialRecommendation :exec
INSERT INTO recommend ("user_ID", "tag_ID", match_int) VALUES ($1, $2, 1)
`

type CreateInitialRecommendationParams struct {
	UserID int32
	TagID  int32
}

func (q *Queries) CreateInitialRecommendation(ctx context.Context, arg CreateInitialRecommendationParams) error {
	_, err := q.db.Exec(ctx, createInitialRecommendation, arg.UserID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tag (tag_name) VALUES ($1) RETURNING "tag_ID", tag_name
`

func (q *Queries) CreateTag(ctx context.Context, tagName string) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, tagName)
	var i Tag
	err := row.Scan(&i.TagID, &i.TagName)
	return i, err
}

const findTagByNormalizedName = `-- name: FindTagByNormalizedName :one
SELECT "tag_ID", tag_name FROM tag
WHERE lower(btrim(tag_name)) = lower(btrim($1::text)) ORDER BY "tag_ID" LIMIT 1
`

func (q *Queries) FindTagByNormalizedName(ctx context.Context, dollar_1 string) (Tag, error) {
	row := q.db.QueryRow(ctx, findTagByNormalizedName, dollar_1)
	var i Tag
	err := row.Scan(&i.TagID, &i.TagName)
	return i, err
}

const lockNormalizedTag = `-- name: LockNormalizedTag :exec

SELECT pg_advisory_xact_lock(hashtext('tag:' || lower(btrim($1::text))))
`

// 表記違い(大文字小文字・前後空白)のタグをGo書き込み同士で重複作成しないよう、
// 正規化したタグ名ごとにトランザクション内の排他ロックを取ってから再検索する。
func (q *Queries) LockNormalizedTag(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockNormalizedTag, dollar_1)
	return err
}
