// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (user_name, password, role) VALUES ($1, $2, $3)
RETURNING "user_ID", user_name, role
`

type CreateUserParams struct {
	UserName string
	Password string
	Role     string
}

type CreateUserRow struct {
	UserID   int32
	UserName string
	Role     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.UserName, arg.Password, arg.Role)
	var i CreateUserRow
	err := row.Scan(&i.UserID, &i.UserName, &i.Role)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT "user_ID", user_name, password, role FROM "user" WHERE user_name = $1
`

func (q *Queries) FindUserByUsername(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, userName)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Password,
		&i.Role,
	)
	return i, err
}
