// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_feedback.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeFeedbackSubmission = `-- name: CompleteFeedbackSubmission :exec
UPDATE feedback_submissions SET status = 'completed', completed_at = $2 WHERE id = $1 AND status = 'partial'
`

type CompleteFeedbackSubmissionParams struct {
	ID          pgtype.UUID
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) CompleteFeedbackSubmission(ctx context.Context, arg CompleteFeedbackSubmissionParams) error {
	_, err := q.db.Exec(ctx, completeFeedbackSubmission, arg.ID, arg.CompletedAt)
	return err
}

const deleteExpiredFeedbackPrompts = `-- name: DeleteExpiredFeedbackPrompts :execrows
DELETE FROM feedback_prompts AS target WHERE target.id IN (
    SELECT candidate.id FROM feedback_prompts AS candidate
    WHERE COALESCE(candidate.finished_at, candidate.shown_at) < $1
    ORDER BY COALESCE(candidate.finished_at, candidate.shown_at)
    LIMIT $2
)
`

type DeleteExpiredFeedbackPromptsParams struct {
	Before    pgtype.Timestamptz
	BatchSize int32
}

// 保持期限（終了日時、未終了なら表示日時）の古い順に、上限件数まで消す。回答などは連鎖して消える
func (q *Queries) DeleteExpiredFeedbackPrompts(ctx context.Context, arg DeleteExpiredFeedbackPromptsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredFeedbackPrompts, arg.Before, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveFeedbackForm = `-- name: GetActiveFeedbackForm :one
SELECT id, form_key, version, title, cooldown_days FROM feedback_forms WHERE status = 'active'
`

type GetActiveFeedbackFormRow struct {
	ID           int64
	FormKey      string
	Version      int32
	Title        string
	CooldownDays int32
}

func (q *Queries) GetActiveFeedbackForm(ctx context.Context) (GetActiveFeedbackFormRow, error) {
	row := q.db.QueryRow(ctx, getActiveFeedbackForm)
	var i GetActiveFeedbackFormRow
	err := row.Scan(
		&i.ID,
		&i.FormKey,
		&i.Version,
		&i.Title,
		&i.CooldownDays,
	)
	return i, err
}

const getFeedbackAnswerScore = `-- name: GetFeedbackAnswerScore :one
SELECT score FROM feedback_answers WHERE submission_id = $1 AND question_id = $2
`

type GetFeedbackAnswerScoreParams struct {
	SubmissionID pgtype.UUID
	QuestionID   int64
}

func (q *Queries) GetFeedbackAnswerScore(ctx context.Context, arg GetFeedbackAnswerScoreParams) (int32, error) {
	row := q.db.QueryRow(ctx, getFeedbackAnswerScore, arg.SubmissionID, arg.QuestionID)
	var score int32
	err := row.Scan(&score)
	return score, err
}

const getFeedbackFormByID = `-- name: GetFeedbackFormByID :one
SELECT id, form_key, version, title, cooldown_days FROM feedback_forms WHERE id = $1
`

type GetFeedbackFormByIDRow struct {
	ID           int64
	FormKey      string
	Version      int32
	Title        string
	CooldownDays int32
}

func (q *Queries) GetFeedbackFormByID(ctx context.Context, id int64) (GetFeedbackFormByIDRow, error) {
	row := q.db.QueryRow(ctx, getFeedbackFormByID, id)
	var i GetFeedbackFormByIDRow
	err := row.Scan(
		&i.ID,
		&i.FormKey,
		&i.Version,
		&i.Title,
		&i.CooldownDays,
	)
	return i, err
}

const getFeedbackSubmissionByPrompt = `-- name: GetFeedbackSubmissionByPrompt :one
SELECT id, status FROM feedback_submissions WHERE prompt_id = $1
`

type GetFeedbackSubmissionByPromptRow struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) GetFeedbackSubmissionByPrompt(ctx context.Context, promptID pgtype.UUID) (GetFeedbackSubmissionByPromptRow, error) {
	row := q.db.QueryRow(ctx, getFeedbackSubmissionByPrompt, promptID)
	var i GetFeedbackSubmissionByPromptRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getFeedbackSubmissionOwner = `-- name: GetFeedbackSubmissionOwner :one
SELECT prompt_id, "user_ID" FROM feedback_submissions WHERE id = $1
`

type GetFeedbackSubmissionOwnerRow struct {
	PromptID pgtype.UUID
	UserID   int32
}

func (q *Queries) GetFeedbackSubmissionOwner(ctx context.Context, id pgtype.UUID) (GetFeedbackSubmissionOwnerRow, error) {
	row := q.db.QueryRow(ctx, getFeedbackSubmissionOwner, id)
	var i GetFeedbackSubmissionOwnerRow
	err := row.Scan(&i.PromptID, &i.UserID)
	return i, err
}

const insertFeedbackAnswer = `-- name: InsertFeedbackAnswer :exec
INSERT INTO feedback_answers (submission_id, form_id, question_id, score) VALUES ($1, $2, $3, $4)
`

type InsertFeedbackAnswerParams struct {
	SubmissionID pgtype.UUID
	FormID       int64
	QuestionID   int64
	Score        int32
}

func (q *Queries) InsertFeedbackAnswer(ctx context.Context, arg InsertFeedbackAnswerParams) error {
	_, err := q.db.Exec(ctx, insertFeedbackAnswer,
		arg.SubmissionID,
		arg.FormID,
		arg.QuestionID,
		arg.Score,
	)
	return err
}

const insertFeedbackPrompt = `-- name: InsertFeedbackPrompt :execrows
INSERT INTO feedback_prompts (id, form_id, "user_ID", shown_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO NOTHING
`

type InsertFeedbackPromptParams struct {
	ID      pgtype.UUID
	FormID  int64
	UserID  int32
	ShownAt pgtype.Timestamptz
}

func (q *Queries) InsertFeedbackPrompt(ctx context.Context, arg InsertFeedbackPromptParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertFeedbackPrompt,
		arg.ID,
		arg.FormID,
		arg.UserID,
		arg.ShownAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertFeedbackSnapshot = `-- name: InsertFeedbackSnapshot :exec
INSERT INTO feedback_interest_snapshots (submission_id, rank, "tag_ID", tag_name, match_int)
VALUES ($1, $2, $3, $4, $5)
`

type InsertFeedbackSnapshotParams struct {
	SubmissionID pgtype.UUID
	Rank         int32
	TagID        pgtype.Int4
	TagName      string
	MatchInt     int32
}

func (q *Queries) InsertFeedbackSnapshot(ctx context.Context, arg InsertFeedbackSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertFeedbackSnapshot,
		arg.SubmissionID,
		arg.Rank,
		arg.TagID,
		arg.TagName,
		arg.MatchInt,
	)
	return err
}

const insertFeedbackSubmission = `-- name: InsertFeedbackSubmission :one
INSERT INTO feedback_submissions (form_id, "user_ID", prompt_id, status, started_at, completed_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertFeedbackSubmissionParams struct {
	FormID      int64
	UserID      int32
	PromptID    pgtype.UUID
	Status      string
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) InsertFeedbackSubmission(ctx context.Context, arg InsertFeedbackSubmissionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertFeedbackSubmission,
		arg.FormID,
		arg.UserID,
		arg.PromptID,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const lastFeedbackPrompt = `-- name: LastFeedbackPrompt :one
SELECT p.id, p.status, p.stage, p.shown_at, s.id AS submission_id, s.status AS submission_status
FROM feedback_prompts p
JOIN feedback_forms f ON f.id = p.form_id
LEFT JOIN feedback_submissions s ON s.prompt_id = p.id
WHERE p."user_ID" = $1 AND f.form_key = $2
ORDER BY p.shown_at DESC, p.id DESC
LIMIT 1
`

type LastFeedbackPromptParams struct {
	UserID  int32
	FormKey string
}

type LastFeedbackPromptRow struct {
	ID               pgtype.UUID
	Status           string
	Stage            string
	ShownAt          pgtype.Timestamptz
	SubmissionID     pgtype.UUID
	SubmissionStatus pgtype.Text
}

// 版をまたいで、同じフォームの直近の表示を返す
func (q *Queries) LastFeedbackPrompt(ctx context.Context, arg LastFeedbackPromptParams) (LastFeedbackPromptRow, error) {
	row := q.db.QueryRow(ctx, lastFeedbackPrompt, arg.UserID, arg.FormKey)
	var i LastFeedbackPromptRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Stage,
		&i.ShownAt,
		&i.SubmissionID,
		&i.SubmissionStatus,
	)
	return i, err
}

const listFeedbackQuestions = `-- name: ListFeedbackQuestions :many
SELECT id, question_key, question_text, sort_order, is_required, display_if_question_id, display_if_score_max
FROM feedback_questions WHERE form_id = $1 ORDER BY sort_order
`

type ListFeedbackQuestionsRow struct {
	ID                  int64
	QuestionKey         string
	QuestionText        string
	SortOrder           int32
	IsRequired          bool
	DisplayIfQuestionID pgtype.Int8
	DisplayIfScoreMax   pgtype.Int4
}

func (q *Queries) ListFeedbackQuestions(ctx context.Context, formID int64) ([]ListFeedbackQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listFeedbackQuestions, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedbackQuestionsRow{}
	for rows.Next() {
		var i ListFeedbackQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionKey,
			&i.QuestionText,
			&i.SortOrder,
			&i.IsRequired,
			&i.DisplayIfQuestionID,
			&i.DisplayIfScoreMax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedbackSnapshotSource = `-- name: ListFeedbackSnapshotSource :many
SELECT r."tag_ID", t.tag_name, r.match_int
FROM recommend r JOIN tag t ON t."tag_ID" = r."tag_ID"
WHERE r."user_ID" = $1
ORDER BY r.match_int DESC, r."tag_ID" ASC
LIMIT 5
`

type ListFeedbackSnapshotSourceRow struct {
	TagID    int32
	TagName  string
	MatchInt int32
}

func (q *Queries) ListFeedbackSnapshotSource(ctx context.Context, userID int32) ([]ListFeedbackSnapshotSourceRow, error) {
	rows, err := q.db.Query(ctx, listFeedbackSnapshotSource, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedbackSnapshotSourceRow{}
	for rows.Next() {
		var i ListFeedbackSnapshotSourceRow
		if err := rows.Scan(&i.TagID, &i.TagName, &i.MatchInt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFeedbackPrompt = `-- name: LockFeedbackPrompt :one
SELECT id, form_id, "user_ID", status, stage, shown_at FROM feedback_prompts WHERE id = $1 FOR UPDATE
`

type LockFeedbackPromptRow struct {
	ID      pgtype.UUID
	FormID  int64
	UserID  int32
	Status  string
	Stage   string
	ShownAt pgtype.Timestamptz
}

func (q *Queries) LockFeedbackPrompt(ctx context.Context, id pgtype.UUID) (LockFeedbackPromptRow, error) {
	row := q.db.QueryRow(ctx, lockFeedbackPrompt, id)
	var i LockFeedbackPromptRow
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.UserID,
		&i.Status,
		&i.Stage,
		&i.ShownAt,
	)
	return i, err
}

const lockFeedbackSubmission = `-- name: LockFeedbackSubmission :one
SELECT id, form_id, "user_ID", prompt_id, status FROM feedback_submissions WHERE id = $1 FOR UPDATE
`

type LockFeedbackSubmissionRow struct {
	ID       pgtype.UUID
	FormID   int64
	UserID   int32
	PromptID pgtype.UUID
	Status   string
}

func (q *Queries) LockFeedbackSubmission(ctx context.Context, id pgtype.UUID) (LockFeedbackSubmissionRow, error) {
	row := q.db.QueryRow(ctx, lockFeedbackSubmission, id)
	var i LockFeedbackSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.UserID,
		&i.PromptID,
		&i.Status,
	)
	return i, err
}

const lockUserFeedbackForm = `-- name: LockUserFeedbackForm :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// 同じ利用者・同じフォームの表示判定を1つずつ行う（まだ表示記録が無い初回でも効く）
func (q *Queries) LockUserFeedbackForm(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, lockUserFeedbackForm, lockKey)
	return err
}

const markFeedbackPromptDismissed = `-- name: MarkFeedbackPromptDismissed :exec
UPDATE feedback_prompts SET status = 'dismissed', finished_at = $2 WHERE id = $1 AND status = 'shown'
`

type MarkFeedbackPromptDismissedParams struct {
	ID         pgtype.UUID
	FinishedAt pgtype.Timestamptz
}

func (q *Queries) MarkFeedbackPromptDismissed(ctx context.Context, arg MarkFeedbackPromptDismissedParams) error {
	_, err := q.db.Exec(ctx, markFeedbackPromptDismissed, arg.ID, arg.FinishedAt)
	return err
}

const markFeedbackPromptFollowup = `-- name: MarkFeedbackPromptFollowup :exec
UPDATE feedback_prompts SET stage = 'followup' WHERE id = $1 AND status = 'shown'
`

func (q *Queries) MarkFeedbackPromptFollowup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markFeedbackPromptFollowup, id)
	return err
}

const markFeedbackPromptSubmitted = `-- name: MarkFeedbackPromptSubmitted :exec
UPDATE feedback_prompts SET status = 'submitted', finished_at = $2 WHERE id = $1 AND status = 'shown'
`

type MarkFeedbackPromptSubmittedParams struct {
	ID         pgtype.UUID
	FinishedAt pgtype.Timestamptz
}

func (q *Queries) MarkFeedbackPromptSubmitted(ctx context.Context, arg MarkFeedbackPromptSubmittedParams) error {
	_, err := q.db.Exec(ctx, markFeedbackPromptSubmitted, arg.ID, arg.FinishedAt)
	return err
}
